### ISSUE TITLE
保存cookies失败

### ISSUE THREAD

**Issue by TonyTong1993** [lilidan/SSWKURL#1]
- (NSArray<NSHTTPCookie *> *)handleHeaderFields:(NSDictionary *)headerFields forURL:(NSURL *)URL {
    NSArray *cookieArray = [NSHTTPCookie cookiesWithResponseHeaderFields:headerFields forURL:URL];
    if (cookieArray != nil) {
        NSHTTPCookieStorage *cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
        for (NSHTTPCookie *cookie in cookieArray) {
            if (cookieFilter(cookie, URL)) {
                [cookieStorage setCookie:cookie];
            }
        }
    }
    return cookieArray;
}

cookiesWithResponseHeaderFields这个方法执行后cookieArra是empty

**Comment by lilidan** [comment]
说明没有Cookie呢,不是所有的网络请求都会set-cookie的
