### ISSUE TITLE
线上环境的可行性

### ISSUE THREAD

**Issue by FoneG** [lilidan/SSWKURL#2]
@修改handlesURLScheme的实现会造成其他衍生问题吗？作者有没有在公司的项目中采用这种方案

遇到一个失败场景
url切换成https://v.youku.com/v_show/id_XNDc1NDI5MzQ0OA==.html 就无法加载成功

**Comment by lilidan** [comment]
正在采用，我看看具体问题是什么

**Comment by lilidan** [comment]
目前还无法支持视频的播放，后续会支持

**Comment by FoneG** [comment]
具体是什么原因造成了解么

**Comment by lilidan** [comment]
没写视频播放的网络请求。。。

**Comment by lilidan** [comment]
视频的网络请求已经完成了，但是现在打开youku还是会跳白屏，试了下b站爱奇艺腾讯视频都没这个问题，不知道youku在页面里做了什么，如果有思路大佬可以分享一下

**Comment by lhkzhl** [comment]
也发现一个加载空白情况http://taobao.com/
